### ISSUE TITLE
Trigger hover for Dropdown Menu

### ISSUE THREAD

**Issue by alekseykurylev** [radix-ui/themes#118]
Hi, I can't add trigger hover for Dropdown Menu. How can I do this? 
![image](https://github.com/radix-ui/themes/assets/8526127/3bd41f0f-e3be-4c14-b59a-97326ecd35b2)

https://github.com/radix-ui/themes/assets/8526127/4f24e826-0d4c-45ce-9b09-dcfd1970f810

**Comment by vladmoroz** [comment]
Dropdown Menu isn't supposed to open on hover. It's not a typical design pattern that we'd plan to support.

Our recommendation is to re-consider your design so that it opens on click, or look into components that are designed to open on hover out of the box:
- [Navigation Menu](https://www.radix-ui.com/primitives/docs/components/navigation-menu)
- [Hover Card](https://www.radix-ui.com/primitives/docs/components/hover-card)
- [Tooltip](https://www.radix-ui.com/primitives/docs/components/tooltip)

**Comment by gustaveWPM** [comment]
> Dropdown Menu isn't supposed to open on hover. It's not a typical design pattern that we'd plan to support.
> 
> Our recommendation is to re-consider your design so that it opens on click, or look into components that are designed to open on hover out of the box:
> 
> * [Navigation Menu](https://www.radix-ui.com/primitives/docs/components/navigation-menu)
> * [Hover Card](https://www.radix-ui.com/primitives/docs/components/hover-card)
> * [Tooltip](https://www.radix-ui.com/primitives/docs/components/tooltip)

Hi,
I'm having the same problem.

I find it a bit annoying to have to define a second "Just" component for this.

Moreover, _dropdowns_ offer a nice enough implementation to nest several of them, whereas it doesn't seem to be the usecase of the Navigation Menu?

I think it's a feature that's desirable. It could be easy to use with a `withHover` flag on `<DropdownMenu />`, or something similar.

I tried wrapping the `<DropdownMenu />` in a `<div>`, then forcing a focus on this wrapper first child (i.e. the trigger), then dispatching a click or press of the enter key to see... This approach doesn't work.

**Comment by vladmoroz** [comment]
> I find it a bit annoying to have to define a second component "Just" for this in my current codebase.

> Moreover, dropdowns offer a nice enough implementation to nest several of them, whereas it doesn't seem to be the usecase of the Navigation Menu?

You can nest Navigation Menus, and yep it is indeed a different component because the behaviour and semantics are different. It is designed exactly for the use-case you have.

The bugs you are having to fix with your custom logic on top of the dropdown menu implementation could be avoided if using the right component.
