### ISSUE TITLE
[Accessibility] Typography font-size ignores accessibility settings

### ISSUE THREAD

**Issue by glung** [radix-ui/themes#121]
**Issue:** Typography font-size ignores accessibility settings. As a consequence, users with disabilities increasing the font-size may not be able to read the text.

**Root cause:** The Radix-Theme expresses [font-size in `px`](https://github.com/radix-ui/themes/blob/bfab82fac4707e5ab633aebd702f5c985c45c019/packages/radix-ui-themes/src/styles/tokens/typography.css#L4) instead of rem.

I know the radix team cares a lot about accessibility, is there an alternative recommendation or is this simply a bug?

**Comment by vladmoroz** [comment]
If you want to use rems throughout your UI, you can [override](https://www.radix-ui.com/themes/docs/theme/token-reference#modifying-tokens) the typographic and space tokens with their rem equivalents.

We are of course aware that rems have the benefit of responding to the browser text size settings, but that's not the only way to increase the font size in a browser. There's also no WCAG success criterion that mandates the use of specific units—using rems is one of the sufficient techniques, while making sure that your UI works with built-in browser zoom is an equivalent sufficient technique as described here:
https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-scale.html
https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/C14
https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G142

We picked px because the ergonomics of modern web development heavily suggest px values, and with that, this makes Radix Themes potentially more compatible with custom components and existing UIs. You can always use your tokens if you prefer another unit.

**Comment by glung** [comment]
That's interesting.

As a user, I am not using any of the techniques to increase the font-size. I did not know that multiple approaches are possible. I looked around, and it seems that a lot of websites use rem for spacing but not font-size. And using zoom is probably a better technique for users. 

I actually removed my glasses :), and noticed that zooming works better for me as it allows me to select the zoom depending on the content (images included). Thank you for taking the time to explain this, and for linking to the corresponding WCAG articles. 

You could basically copy/paste your message in one of the doc sections.

**Comment by robphoenix** [comment]
Sorry to add to a closed issue, and obviously feel free to ignore, but I was interested in this reasoning:

> the ergonomics of modern web development heavily suggest px values

@vladmoroz Would you mind elaborating on this?

**Comment by vladmoroz** [comment]
> @vladmoroz Would you mind elaborating on this? (fwiw I'm not disagreeing, so not asking you to justify it, I'm more curious what's led you to this? 🙂 )

Just from the experience working in different teams, realistically it tends to be really hard to track down all the `px` values that are so easy to sneak in from inline React or CSS-in-JS styles, since numbers are interpreted as pixels (e.g. think `width: 400`) and different teams have different levels of rigour. That's why the `rem`s aren't default, as there's a risk that people who do need larger fonts will get a half-broken experience on a website that's part `rem` part `px`.

**Comment by robphoenix** [comment]
Ok, that's interesting, thanks. So, the expectation is devs are more likely to use px values outside of provided components, therefore using them in the UI library actually provides more consistent expectations. That makes sense, appreciate you explaining this 🙇🏻
