### ISSUE TITLE
button's classname passed from UI doesn't take precedence(unable to change color)

### ISSUE THREAD

**Issue by triptu** [radix-ui/themes#16]
hi folks! lovely library. I was just wondering if passing the incoming props before inbuilt class names is intentional?

What I'm trying to do - 

```
<Button className="fancy-gradient-button" />

<Button className="disabled-btn" />
```

But in this the background of the button doesn't take precedence, as the classnames from the library come later. This behaviour in general is common for all components. Am I missing something obvious or is this expected(which also makes sense for consistency)?

**Comment by jd-carroll** [comment]
I don't think that's how this all works. Would need to see what your actual classes contain, but if you add a normal css class (without variables), of course the child elements aren't going to receive the color.

For your approach to work, your class would need to contain the proper [color tokens](https://www.radix-ui.com/themes/docs/theme/token-reference) used by `Button`.

Could be wrong, but that's how I believe this works.

Also, (as someone who is just learning all of this), I wouldn't use that approach. I'd follow [what is described in the docs](https://www.radix-ui.com/themes/docs/components/button#api-reference) and set the accent color directly.

**Comment by vladmoroz** [comment]
You are probably running into a specificity issue with your CSS. 

Most button variants have `0, 2, 0` specificity on the rules that define the background color (for the regular rest state, at least):

<img width="463" alt="image" src="https://github.com/radix-ui/themes/assets/8441036/cd6ade5a-82e4-4b00-8e13-0b75bba69731">

***

The best way to override base styles in your example is to create a matching rule in your CSS:

```css
.my-fancy-button.rt-BaseButton.rt-variant-solid {
  background-image: ...
}
```

Please note that **we don’t encourage component customization like this** as it's fragile because it relies on internal implementation details, which may change down the line. In your case, you'd have to also recreate all the states.

Your safest bet is to tweak the base CSS variables that we provide. Otherwise, if a specific Radix Themes component doesn’t fit your use-case, it's always easier to create your own component which you’d have full control over.

**Comment by brettinternet** [comment]
You could also use [CSS Layers](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer) to control specificity. For example, with panda-css in `index.css`:

```css
@layer reset, radix, base, tokens, recipes, utilities;

@import "@radix-ui/themes/styles.css" layer(radix);
```
