### ISSUE TITLE
Card Component background color and size not consistent depending on the variant

### ISSUE THREAD

**Issue by Saadchr** [radix-ui/themes#163]
Hi,

I am trying to style the Card component but I don't get why:

1. "classic" and "surface" variants cannot have a background color applied, it has a white background color by default.
2. "ghost" variant does accept a background color but its size seems to scale

https://github.com/Saadchr/darkMode
https://dark-mode-wine.vercel.app/

![CleanShot 2023-11-26 at 16 51 14@2x](https://github.com/radix-ui/themes/assets/74289775/37f5adcd-7e6b-4f7b-87a1-42062bd3fb2c)

**Comment by vladmoroz** [comment]
I'm not sure what you mean by "cannot have a background color applied" or "does accept a background color" – there are no props to customize the background in either variant.

As for the the ghost variant, it has no visible padding intentionally so that it can be used in a layout like regular content, but have an outer background on hover. See https://github.com/radix-ui/themes/issues/113#issuecomment-1755711960 for the example.

If these components aren't a good fit, you are better off building your own version rather than trying to coerce them to work differently.
