### ISSUE TITLE
The dark theme has not worked properly.

### ISSUE THREAD

**Issue by zmzimpl** [radix-ui/themes#22]
It seems that the issue arises after setting appearance="dark" without properly setting the HTML attributes class="light-theme" and style="color-scheme: light;".

![image](https://github.com/radix-ui/themes/assets/27490895/42eaeaef-8f72-463a-ab64-68820247be2c)

**Comment by zmzimpl** [comment]
`@radix-ui/themes`  version: 1.0.0

**Comment by zmzimpl** [comment]
I cloned the source code attempting to fix this issue, but encountered an error when running it:
```
D:\dev\github\themes>npm run dev  

> dev
> turbo run dev --no-cache --continue

• Running dev
• Remote caching disabled
root task dev (turbo run dev --no-cache --continue) looks like it invokes turbo and might cause a loop

No tasks were executed as part of this run.

 Tasks:    0 successful, 0 total
Cached:    0 cached, 0 total
  Time:    171ms

 ERROR  run failed: command  exited (1)
```
I'm wondering what the issue is, as I couldn't find an answer on Google. Perhaps you might know?

**Comment by jd-carroll** [comment]
I can confirm this behavior, here is a codesandbox which demonstrates it:
https://codesandbox.io/s/intelligent-framework-2xqjp8?file=/src/App.tsx

The issue is here:
https://github.com/radix-ui/themes/blob/39f5a438db0d8496134d4bc35d71899fee1b2562/packages/radix-ui-themes/src/theme.tsx#L152-L159

When the root theme element is rendered, the `useContext` call will still return undefined. So if you look at the example, it actually appears to be using some gray palette and not an actual dark theme. 

If you move the `appearance="dark"` to the second `Theme` component, it works as expected.

Not sure what the best fix would be, but a fix would be changing the [appearance prop](https://github.com/radix-ui/themes/blob/39f5a438db0d8496134d4bc35d71899fee1b2562/packages/radix-ui-themes/src/theme.tsx#L159) to something like:
```typescript
  appearance = props.appearance ?? context?.appearance ?? themePropDefs.appearance.default,
```

This way, the Theme component always prefers component props and then falls back to context and default values.

Note: A temporary workaround would be to do something like:
```jsx
<Theme appearance="dark">
  <Theme>
    <MyApp />
  </Theme>
</Theme>
```

(Looks ridiculous, but ensures the second theme receives the desired props)

**Comment by jd-carroll** [comment]
So my comment above is definitely _wrong_ (would help if I could read code correctly 😬 )

**However**, the codesandbox link still reproduces the issue...

Wondering if it is a React 17 vs 18 thing

**Comment by sourcec0de** [comment]
I hacked this to enable dark mode in vite.
If that's all you want like me, then you can add this to your `<html>` tag.
```html
<html lang="en" class="dark-theme" style="color-scheme: dark;"></html>
```

**Comment by needim** [comment]
you need to manage dark/light theme switching. 

check this CRA example: https://codesandbox.io/s/radix-ui-themes-cra-hvw2lk?file=/src/App.js

follow the docs: https://www.radix-ui.com/themes/docs/theme/dark-mode#with-next-themes

**Comment by vgrafe** [comment]
Cross-posting my solution from another issue: https://github.com/radix-ui/themes/issues/26#issuecomment-1703576566

**Comment by stvncode** [comment]
The problem is that it's working with the panel but not with the onAppearanceChange. It doesn't change the html element. I did a quick fix by doing it myself.

In the html attribute : `<html lang="en" class="dark" suppressHydrationWarning>`

Component to change the value : `import { HeaderWrapper } from './Header.styles'
import { Avatar, Button, Flex, Text, useThemeContext } from '@radix-ui/themes'
import { MoonIcon, PersonIcon, SunIcon } from '@radix-ui/react-icons'
import { ThemeAppearance } from 'domain/theme'
import { match } from 'ts-pattern'


export const Header = () => {
    const { appearance, onAppearanceChange } = useThemeContext()

    const isDark = appearance !== ThemeAppearance.Light

    const onThemeChange = () =>
        onAppearanceChange(match(appearance)
            .with(ThemeAppearance.Light, () => {
                document.documentElement.setAttribute('class', 'dark-theme');
                document.documentElement.style.colorScheme = 'dark'
                return ThemeAppearance.Dark
            })
            .otherwise(() => {
                document.documentElement.setAttribute('class', 'light-theme');
                document.documentElement.style.colorScheme = 'light'

                return ThemeAppearance.Light
            })
        )

    return (
        <HeaderWrapper justify="between">
            <Text size="6" weight="bold">Stvncode</Text>
            <Flex align="center" gap="3">
                <Button size="1" radius='full' onClick={onThemeChange}>
                    {isDark ? <MoonIcon /> : <SunIcon />}
                </Button>
                <Avatar size="1" fallback={<PersonIcon />} />
            </Flex>
        </HeaderWrapper >
    )
}
`
And in your theme provider : `<Theme color="dark" accentColor="indigo">`

**Comment by jdukleth** [comment]
> The problem is that it's working with the panel but not with the onAppearanceChange. It doesn't change the html element. I did a quick fix by doing it myself.
> 
> In the html attribute : `<html lang="en" class="dark" suppressHydrationWarning>`

This is not good. Suppressing hydration warnings in your entire app can lead to you missing actual hydration problems that should be addressed.

**Comment by jdukleth** [comment]
I fixed it with the following:

`<html lang="en" className="dark-theme dark" style={{ colorScheme: 'dark' }}>`

via the docs: https://www.radix-ui.com/themes/docs/theme/dark-mode#with-next-themes

BUT my question is... I am only using Radix Themes (browser plugins off too). So, why on earth do I need to include those attributes to have it fix itself?
