### ISSUE TITLE
[Theme Appearance] The appearance is always `light` in Next.js `not-found` and `error` pages

### ISSUE THREAD

**Issue by simonfarah** [radix-ui/themes#280]
I have a Next.js 14 project in development, and I am having this issue. I have my Radix Theme provider setup correctly in the root layout with a dark appearance and everything's working great. However, in the Next.js `not-found` and `error` pages, the appearance is always light unless I manually add again the provider to those pages, and end up having two radix providers on top of each other. I noticed the `dark` class name disappear from the html element, and that's maybe due to how Next.js behave in those routes or maybe a Radix Theme bug?

**Comment by vladmoroz** [comment]
This is probably a Next.js quirk. I vaguely remember that we ran into a similar issue in one of our projects, but can’t remember the exact resolution because we've changed more to how theming works there after. Some ideas I'd suggest, assuming you are using dark mode only:
- Remove `appearance="dark"` from the `Theme` provider and manually set `<html className="dark" style={{ color-scheme: "dark" }}>` in your root layout.
- Or, if the workaround with nested Theme providers works, continue using that—it’s fine technically, they are designed to be nested.
