### ISSUE TITLE
Package Exports Broken

### ISSUE THREAD

**Issue by jd-carroll** [radix-ui/themes#333]
While not part of the core component "api's", the utilities under `helpers` and `props` are very useful for people writing third-party components.

Re-using the utilities developed there allows our components to integrate seamlessly with the core radix components :heart:

**Comment by jd-carroll** [comment]
\+ elements from `color.prop`

**Comment by jd-carroll** [comment]
Ohh, interesting, they already are... However, **the exports are configured incorrectly**.

The structure of the package currently is:
```
  "type": "commonjs",
  "main": "./dist/cjs/index.js",
  "types": "./dist/cjs/index.d.ts",
  "module": "./dist/esm/index.js",
  "style": "./styles.css",
  "exports": {
```

The problem is the `"type": "commonjs"`. This forces the module loader to completely ignore the `"exports"`, which is the only place props and helpers are exported.

While I am not an expert, I feel like the structure should be like:
```
  "type": "module",
  "style": "./styles.css",
  "exports": {
```

Yes, this may mean that there is the _possibility_ that some consumers are unable to load the package because their environment doesn't know how to interact with the module structure. 

But I think practically speaking, this is unrealistic because all consumers are (likely) using a bundler capable of understanding the module type.

**Comment by jd-carroll** [comment]
I just tried playing around with my suggestion above in my `node_modules` and it didn't work. So I think the best approach is to re-export through the root `index.ts`

**Comment by jd-carroll** [comment]
\+ Export `ThemeProps`  in `src/components/index.ts`

New export should be:
```
export { Theme, ThemeProps, useThemeContext } from './theme.js';
```

**Comment by vladmoroz** [comment]
Package exports are not broken, not at all.

Props and helpers are exported from `@radix-ui/themes/props` and `@radix-ui/themes/helpers`, however:
- They are not going to be documented or covered by semver yet
- Your project needs `"moduleResolution": "Node16"` or `"moduleResolution": "NodeNext"` to support subpath exports
  - Under this module resolution, problems with other dependencies might be common, as a lot of JS packages don't have their `package.json` files configured correctly
  - Alternatively, import what you need using the file path directly, e.g. `@radix-ui/themes/dist/.../index.js` etc

> The problem is the `"type": "commonjs"`. This forces the module loader to completely ignore the `"exports"`, which is the only place props and helpers are exported.

`type` field isn't related to `exports` field. It impacts only whether `.js` files should be interpreted as CommonJS or ESM.

> Yes, this may mean that there is the _possibility_ that some consumers are unable to load the package because their environment doesn't know how to interact with the module structure.
> 
> But I think practically speaking, this is unrealistic because all consumers are (likely) using a bundler capable of understanding the module type

Radix Themes dist contains both ESM and CommonJS bundles. It’s CommonJS by default because that's the least problematic option in the vast majority of environments today; however, `package.json` contains everything needed for the dev tools to discover the ESM version if that’s what a particular program would be looking for.

> So I think the best approach is to re-export through the root index.ts

We don't plan to export the unstable APIs from index

**Comment by jd-carroll** [comment]
While I agree with you, the exports are not broken and I should have updated the title (again), the type definitions are. For anyone not using ESModules they will only read the types from the `"types": "./dist/cjs/index.d.ts",`.

**Comment by benoitgrelard** [comment]
@vladmoroz probably need to do the same as we do in primitives, were types get their own exports too: https://github.com/radix-ui/primitives/blob/main/packages/react/accordion/package.json#L5-L15

We basically duplicate them and rename extension as part of the build process.

**Comment by vladmoroz** [comment]
> the type definitions are. For anyone not using ESModules they will only read the types from the `"types": "./dist/cjs/index.d.ts",`

I don’t follow, what’s the problem exactly? The project is set up in such a way that CommonJS projects will use types and code from `dist/cjs`, and ESM projects will use those in `dist/esm`

**Comment by vladmoroz** [comment]
> @vladmoroz probably need to do the same as we do in primitives, were types get their own exports too: https://github.com/radix-ui/primitives/blob/main/packages/react/accordion/package.json#L5-L15
> 
> We basically duplicate them and rename extension as part of the build process.

Don't think we need to, I believe everything already works correctly. I had tested this in different setups during that PR to make Radix Themes ESM-compatible.

**Comment by benoitgrelard** [comment]
Oh yeah they're already setup correctly! My bad, yeah should be no problem then.
