### ISSUE TITLE
[Feature Request] Allow Box to be rendered as semantic section elements like <nav>

### ISSUE THREAD

**Issue by zmillman** [radix-ui/themes#547]
Most a11y auditing tools expect pages to define [content sections](https://developer.mozilla.org/en-US/docs/Web/HTML/Element#content_sectioning) like `<nav>` and `<main>` to help screenreaders skip to the page content.

I expected to be able write something like this but got a `Type '"nav"' is not assignable to type '"span" | "div" | undefined'.` error:

```ts
const TopBar = (props) => {
  return <Box as="nav" className="TopBar">
    {props.children}
  </Box>
};
```

There's a workaround of `<Box className="TopBar" asChild><nav>{props.children}</nav></Box>` but that feels a little messier.

This should probably work the same for other semantic section-related elements like `<header>`, `<footer>`, etc.

**Comment by vladmoroz** [comment]
`as` prop is there to improve ergonomics for the most common tags, use `asChild` for everything else. There’s nothing messy about it, that's why it's there in the first place.

Usually you wouldn't have more than a couple instances of a `nav` or a `header` in your app anyway.

Otherwise, there's just a lot possible of HTML tags, and we had to draw a line somewhere.
