### ISSUE TITLE
The ghost button "breaks" the vertical alignment

### ISSUE THREAD

**Issue by eintxaurtieta** [radix-ui/themes#87]
Hey ✋ 
First of all congratulations with this amazing product! I've been using radix primitives for a long time and you guys rock!

That said, I'm having some issues with the ghost button. I've read in the docs that "Ghost buttons behave differently in layout as they use a negative margin to optically align themselves against their siblings while maintaining their padded active and hover states", and while this sounds amazing and a detail that I love, when I try to put two different buttons, let's say a `solid` and a `ghost` variant in a vertical position, that adjustment is "breaking" the alignment.

Do you guys have some sort of recommendations for this case? Should the `ghost` variant have a way in which those adjustments are not applied if specified?

Thanks in advance!

![Screenshot 2023-09-25 at 17 33 42](https://github.com/radix-ui/themes/assets/24615080/a754da4f-054f-4797-8c3b-14c4473556d1)

**Comment by vladmoroz** [comment]
Hey, this is to make it possible to space the ghost buttons consistently in situations like this:
https://themes-playground-modulz.vercel.app/ghost-balance

You could have overriden the margin and padding to match the other button variants, but to be fair your example doesn’t feel like a typical layout with the button component. It looks like a navigation menu, and I’d suggest you style it manually using the spacing and color tokens provided by Radix Themes, so that it matches the look and feel of other components.

**Comment by eintxaurtieta** [comment]
Replicating it was my first instinct yes.
Thanks for the quick response, keep up the great work!
